name: Web App (CI/CD)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}


    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install 
        pipenv install --dev
        
        
    - name: Testing
      run: |
        pipenv run pytest