name: Web App (CI/CD)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}


    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install 
        pipenv install --dev
        
        
    - name: Testing
      run: |
        pipenv run pytest
    
    - name: Docker login 
      uses: docker/login-action@v2 
      with: 
        username: jladrover 
        password: ${{ secrets.DOCKER_PASSWORD }} 
    
    - name: Docker data 
      id: meta 
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38 
      with: 
        images: jladrover/league_query 
    
    - name: Docker build and push  
      run: | 
        docker-compose build 
        docker-compose up -d 
        docker-compose push
